---
# Automatic testing
#

name: Tests

# Controls when the action will run. Triggers the workflow on:
#   * push on any branch.
#   * tag creation for tags beginning with a 'v'
#   * pull requests
on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["*"]

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Prepare packages
        run: |
          sudo apt-get install -y python3 virtualenv
          virtualenv -p python3 venv
          source venv/bin/activate && \
            pip install -r requirements.txt

      - name: Run the coverage tests
        run: |
          source venv/bin/activate && \
            timeout 180 make coverage
